### ISSUE TITLE
Bug : "500 Internal Servor Error" au moment de cliquer sur le nombre de fois qu'un membre a été remercié depuis n'importe quel message du fofo

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#122]

**Comment by elpiolito** [comment]
Je rajoute que ça le fait aussi sur la liste des remerciements.
Erreur servuer, besoin des accès serveur

**Comment by elpiolito** [comment]
Problème de mod_rewrite : pas de soucis sur du Apache, il faudra jeter un oeil sur la conf Nginx, si possible

**Comment by elpiolito** [comment]
Déplacée : https://github.com/serieall/themeForum/issues/3
