### ISSUE TITLE
Bug responsive : accéder aux notifications du site (cf Altair)

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#124]

**Comment by elpiolito** [comment]
Détail ?

**Comment by MarieOphelie** [comment]
Je pense que ça fait référence à ce post d'Altaïr : https://forum.serieall.fr/viewtopic.php?f=13&t=14#p44
Je l'ai relancée sur le forum.

**Comment by elpiolito** [comment]
A mon avis, c'est plus d'actualité, on peut clore (si ça l'est, elle a qu'à répondre...)

**Comment by MarieOphelie** [comment]
Oui je suis ok avec ce principe. :)

**Comment by elpiolito** [comment]
Un bug de moins :p
