### ISSUE TITLE
Forum : les liens externes ne s'ouvrent pas automatiquement dans un nouvel onglet

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#128]
Exemple : https://forum.serieall.fr/viewtopic.php?p=53#p53

**Comment by elpiolito** [comment]
Uhm, je suis mitigé sur celle-là parce que le comportement sur internet pour les liens, d'après la norme, c'est d'ouvrir au même endroit et de ne pas forcé l'ouverture dans une autre fenêtre/onglet. Donc le forum est conforme à la norme (peut-être que l'ancien ne l'était pas, je ne sais pas), je ne sais même pas si c'est techniquement possible de le faire sur le forum.

Perso, j'utilise toujours le clic molette pour ouvrir les liens dans un nouvel onglet :)

**Comment by GalaxSerieAll** [comment]
Dac, moi aussi en général j'utilise toujours le click molette, mais j'avais testé avec un click simple et je ne m'attendais pas à ce que je perde la page. Faire "précédent" étant plus fastidieux et demandant deux fois plus de temps de chargement (pour ouvrir le lien et pour revenir ensuite) que simplement "continuer la lecture en attendant que l'onglet soit ouvert" puis "fermer l'onglet" qui ne demande aucun temps d'attente.

Mais si c'est la norme internet okay pas de souci on peut laisser. Je suis juste contre la norme alors :p
