### ISSUE TITLE
Forum : absence distinction logo "pas de nvx messages/nvx messages" cf description

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#129]
Plusieurs membres ont reporté le fait de ne jamais voir le cercle rouge (Koss notamment), et globalement la distinction entre les deux n'est pas évidente même pour ceux pour qui ça marche proprement : un remplissage du cercle (avec un large point rouge par exemple) serait peut-être une bonne idée ? exemple : http://image.noelshack.com/fichiers/2019/05/7/1549234702-icone-new-mess-forum.jpg

**Comment by GalaxSerieAll** [comment]
Ou avec le panda : http://image.noelshack.com/fichiers/2019/06/1/1549242665-logo-new-mess-panda.jpg ;)

**Comment by elpiolito** [comment]
Solution : consulter un ophtalmo et acheter des lunettes :p 
Nécessite de modifier le code du template du forum, à voir ce qu'il est possible de faire

**Comment by elpiolito** [comment]
Je kiffe la solution du panda, le soucis c'est qu'une image à l'intérieur du rond est utilisé par plein de choses comme : les topics accrochés (ils ont un ! au milieu), les "hots topics" qui ont une flamme au milieu, un i pour les annonces, etc. J'essaye de voir ce que je peux faire

**Comment by elpiolito** [comment]
Done avec un panda :-p
