### ISSUE TITLE
Forum : image d'index ne renvoie pas à l'index du forum

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#130]
Rend assez difficile sur mobile le fait de revenir à l'index, alors que "retour sur le site" apparaît en premier, est par définition plus long et donc plus voyant et accessible que "Forum" juste à sa droite, et juste le simple réflexe de cliquer sur le logo devrait nous renvoyer sur le forum. Possibilité de créer un autre logo avec écrit "forum" juste en dessous pour rendre ça plus clair si besoin ! Exemple : http://image.noelshack.com/fichiers/2019/06/1/1549236843-logo-forum.jpg

**Comment by elpiolito** [comment]
La conf fait : logo + lien "retour vers le site" sur le même paramètre. Si je retire, il n'y a plus de lien "retour vers le site". Je vais voir si possible de modifier directement le code :)

**Comment by elpiolito** [comment]
Done
