### ISSUE TITLE
Enhancement site - classements à afficher par TOP cf description

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#133]
Actuellement les classement sur les profils et le site général sont alternatifs : Top série, Flop série, Top saison, Flop saison, etc.
Il faudrait leur redonner une classification par type : tous les tops puis tous les flops. Ce qui donnerait donc : Top série, Top saison, top épisodes, etc. Les gens s'en fichent un peu des flops surtout que sur notre site c'est conditionné au nombre de notes.

**Comment by elpiolito** [comment]
Euh, c'est super gratuit ça quand même : "les gens s'en fichent un peu des flops". 

Qu'est ce que te fait dire ça ? Tu te bases sur ta propre expérience ou tu as mené un sondage sur les membres ?
