### ISSUE TITLE
Enhancement site : réduire la taille de l'encadré de l'information d'un épisode

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#135]
Sachant que 95% des épisodes du site n'ont pas de résumé, avoir un aussi gros encadré pour seulement deux dates de diffusion, c'est trop. Sur mon écran de PC, ça m'empeche de voir "Derniera avis" sans scroller presque une page entière.

**Comment by elpiolito** [comment]
Change de PC :)

Plus sérieusement, les nouvelles synchro TVDB récupèrent beaucoup plus de résumé et comblent les trous. Est-ce que cet enhancement est toujours valide ?

**Comment by GalaxSerieAll** [comment]
Les résumés ne sont en fait pas le problème,
le problème est le fait d'avoir un encadré simplement pour deux dates de diffusion, avec un deuxième onglet pour une liste de noms.
J'aurais aimé remplacer l'onglet "Fiche Technique" par en fait un bouton qui par défaut, masque les infos, et si on clique dessus, déroule les infos (les infos des deux précédents onglets, donc : dates de diffusion et noms)

(et la synchro TVDB pour l'instant, c'est pas encore 100% ça, faut que je fasse toutes les modifs à la main + forcer la MAJ de plein de vieilles séries ^^)

**Comment by youkoulayley** [comment]
Est-ce que quelque chose comme ça ça te va ?
![Capture d’écran du 2019-10-04 11-56-54](https://user-images.githubusercontent.com/2247492/66199106-35012700-e69e-11e9-984d-c317335336d8.png)
