### ISSUE TITLE
Enhancement site : afficher de quel épisode parle-t-on après avoir affiché "lire l'avis complet" depuis une fiche épisode

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#136]
Cf. Altair dans le topic Questions sur la V2, cela aurait parfaitement sa place à côté du mot "Avis"

**Comment by youkoulayley** [comment]
Si je n'm'abuse, ça a été fait ça non ?

**Comment by elpiolito** [comment]
Je pense que le déport des avis sur les pages saisons/épisodes résous le soucis oui. A confirmer.
