### ISSUE TITLE
Bug site : quand on édite son avis, on est amené sur une page où il y a juste de marqué : "[ ]".

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#141]

**Comment by elpiolito** [comment]
Je n'arrive pas à reproduire perso. Une page en particulier ? Une façon de faire ?

**Comment by elpiolito** [comment]
Ok, reproduis mais je ne sais pas trop comment :-(

**Comment by MarieOphelie** [comment]
Quand on crée un avis aussi, ça le fait. Bon je ne sais pas si ça fait longtemps ou pas vu que je ne laisse presque jamais d'avis, mais pour les quelques avis que j'ai posés dernièrement sur Fleabag, ça me l'a fait à chaque fois

**Comment by GalaxSerieAll** [comment]
Ca ne me l'a plus fait depuis très longtemps. Possible que ce soit parti avec une autre modification ?

**Comment by elpiolito** [comment]
Si, c'est toujours là. Mais ça ne le fait que sur la page 'Avis" et pas depuis la page épisode. Comme maintenant vous écrivez vos avis depuis la page épisode et plus depuis la page avis, vous n'avez plus le soucis :) 
Mais c'est un truc vraiment bizarre, j'ai pas eu le temps de creuser beaucoup.

**Comment by youkoulayley** [comment]
Corrigé
