### ISSUE TITLE
Enhancement/Bug site : le cercle de couleur lié à la moyenne d'une série est gris anormalement

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#142]
12.95 pour Sex Education et le cercle est gris ? Je pense que le gris doit uniquement apparaître entre 10 et 12. Au-delà de 12 : nuances de vert, en-dessous de 10 : nuances de rouge. A discuter avec les autres membres ? (ça reste mineur)

**Comment by elpiolito** [comment]
Finalement, je bascule en vert à partir de 12 ? Ou à partir de 13 ?

**Comment by MarieOphelie** [comment]
D'accord avec Galax mais question quand même posée sur le forum pour avoir plusieurs avis : https://forum.serieall.fr/viewtopic.php?f=13&t=14&p=1924#p1924

**Comment by MarieOphelie** [comment]
Trois réponses positives à la question, je pense qu'on peut faire la modif du coup. :) Il faudrait donc partir sur :
- Note de 1 à 9 inclus : rouge (défavorable)
- Note de 10 à 12 inclus : gris (neutre)
- Note de 13 à 20 inclus : vert (favorable)

- Moyenne de 1 à 9,99 : rouge (défavorable)
- Moyenne de 10 à 12,99 : gris (neutre)
- Moyenne de 13 à 20 : vert (favorable)
