### ISSUE TITLE
Enhancement crucial site : afficher liste séries en cours depuis index

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#145]
Depuis le menu déroulant en haut à droite de notre profil membre, en-dessous de "se déconnecter" par exemple, il faudrait une liste "Mes séries :" suivies par toutes les séries renseignées comme "en cours". C'est très fastidieux à l'heure actuelle d'accéder aux séries et vu qu'on a facilité la mise à jour de notre profil séries (avec les boutons de MAJ de statut d'une série depuis la fiche d'une série) il serait logique qu'on s'en serve encore, c'est une grosse fonctionnalité qu'il manque

**Comment by youkoulayley** [comment]
Section ajoutée entre Profil et Se déconnecter. :)
