### ISSUE TITLE
Bug forum : le souvenir de connexion ne fonctionne pas

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#146]

**Comment by elpiolito** [comment]
A priori, combo règles de sécurité forum + durée de session.
En cours d'investigation pour voir ce qui peut être amélioré

**Comment by elpiolito** [comment]
Possiblement la règle "Contrôle navigateur" à désactiver. 
Je lance un test

**Comment by elpiolito** [comment]
Tout est désactivé et toujours rien. Je soupçonne un soucis de conf avec Nginx, je vais tester

**Comment by elpiolito** [comment]
Déplacé : https://github.com/serieall/themeForum/issues/4
