### ISSUE TITLE
Enhancement important site : repenser la page des "avis complets"

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#150]
- je trouve que c'est compliqué d'aller lire les commentaires : cliquer sur le lien du fil d'actualité, puis cliquer sur "lire l'avis en entier" - pourquoi ne pas aller directement sur la page des avis complets ? 
- Plus globalement, je ne vois pas bien l'utilité de cette page avec seulement les premières lignes des avis... 
- c'est dommage qu'on ne puisse plus voir les notes qui correspondent à l'épisode dont on visionne les commentaires sur la page des avis complets

> je pense que la page des avis complets est à supprimer,
Premièrement il faudrait que tous les avis soient affichés dès qu'on clique sur un épisode.
Deuxièmement Il faudrait que l'aperçu des avis sur la liste des avis "normaux" soit toujours un aperçu, mais que le bouton pour accéder aux avis complets ne fassent que dérouler (comme le fil de commentaires actuellement, ou comme les anciens avis sur la V1 en fait)
Essentiellement, faire disparaitre la page "avis complet". Et que le volet "Avis" dans le menu sous l'image d'une série (là où il y a Accueil, saison, etc.) soit : soit supprimé, soit remplacé par une sorte de hub avec la liste de tous les avis (série, saison, et tous les épisodes)

**Comment by elpiolito** [comment]
Affichage de tous les avis de l'épisode sur la page épisode. 
Cela devrait le faire temporairement pour une bonne partie des cas d'usages. 
A poursuivre sur la fiche saison
