### ISSUE TITLE
Passage à la V2 avis Site : remettre les "sauts à la ligne" des anciens longs avis

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#152]

**Comment by GalaxSerieAll** [comment]
Je relance car j'ai une petite question : en apparence tout va bien, les avis ont tous des sauts de ligne, même le sien, sur toutes les pages.
Par contre, notre "aperçu d'avis" (situé en bas de page toujours) est encore un gros pavé. Ce n'est pas grave en soi car on peut toujours avoir la version "aérée" de notre propre avis en le recherchant parmi tous les avis. 
Ce qui est problématique c'est que si on veut modifier notre avis, automatiquement le texte rajouté est le gros bloc.

Est-ce qu'il s'agit d'un oubli facile à corriger ? Ou est-ce que ça va plus loin que ça et ça demanderait encore d'autres manip' ?

Dans le deuxième cas tant pis car en soi on peut juste copier coller notre avis aéré "public" dans notre bloc texte, donc il y a une solution. Mais je demande quand même :)

**Comment by elpiolito** [comment]
Rah, putain, je croyais qu'ils passaient tous par le même tuyau, j'ai oublié ceux-là.
Je vais corriger un de ces quatre, il y en a pas pour long.

**Comment by elpiolito** [comment]
Rah, putain, je croyais qu'ils passaient tous par le même tuyau, j'ai oublié ceux-là.
Je vais corriger un de ces quatre, il y en a pas pour long.
