### ISSUE TITLE
Enhancement site : ajouter la date de diffusion du premier épisode de la série dans l'une des infos principales de la série

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#160]
Exemple : https://serieall.fr/saison/fleabag/1 sous "25 min", il reste pile de la place pour UNE info : pourquoi pas la date de diffusion ? C'est suffisamment essentiel et pour écrire une news sur Fleabag j'ai voulu chercher sa date de diffusion et cela m'a apparu étonnant qu'elle n'y soit pas immédiatement.

**Comment by GalaxSerieAll** [comment]
J'en remets une couche : quand on veut édit depuis l'admin les infos principales concernant une série, tous les 5 renseignements présents sous le résumé de la série dans la fiche série sont présents (c'est probablement vers là que le code prend l'info d'ailleurs)... ainsi que la date de diffusion originale, JJ/MM/Année, il faudrait donc juste créer le 6ème chemin.

J'ai noté aussi que sur la page d'accueil puisque la liste des saisons avec épisodes n'est pas visible directement, il est donc impossible de connaître la date de diffusion de la série avec un seul clic, ça nécessite au moins de naviguer sur 2 pages.

**Comment by GalaxSerieAll** [comment]
Je relance pour savoir si cet ajout peut être fait ou pas et concrètement à quel point il est difficile (pour sa mise en place je sais que ce n'est pas un bug donc pas urgent)

**Comment by elpiolito** [comment]
Je n'ai pas du tout regardé.

D'ailleurs, est ce que c'est la date du premier épisode qui est importante ou juste l'année serait suffisante ? Perso, j'aurais tendance à dire l'année "c'est une série de 2015" mais je peux entendre la date complète.

L'idéal, plutôt que de t'ajouter un champ supplémentaire d'ailleurs, c'est tout simplement de prendre la première date de diffusion du premier épisode, que l'on a déjà. Au moins, la date sera toujours juste vis à vis du premier épisode.

**Comment by GalaxSerieAll** [comment]
> D'ailleurs, est ce que c'est la date du premier épisode qui est importante ou juste l'année serait suffisante ? Perso, j'aurais tendance à dire l'année "c'est une série de 2015" mais je peux entendre la date complète.

Les deux vont :) Je trouve l'année tout à fait suffisante (et mieux, perso).

> L'idéal, plutôt que de t'ajouter un champ supplémentaire d'ailleurs, c'est tout simplement de prendre la première date de diffusion du premier épisode, que l'on a déjà. Au moins, la date sera toujours juste vis à vis du premier épisode.

Je... n'ai pas compris. Tu dis que finalement c'est mieux de prendre la date de l'épisode ?

**Comment by elpiolito** [comment]
> Je... n'ai pas compris. Tu dis que finalement c'est mieux de prendre la date de l'épisode ?

Oui.
date de diffusion du premier épisode = date de première diffusion de la série, non ? Donc pourquoi s'emmerder à saisir 2 fois la donnée alors qu'on l'a déjà ?

**Comment by youkoulayley** [comment]
Done
