### ISSUE TITLE
Bug site admin : impossible de supprimer une image de la base de données (clique droit -> ajouter à la corbeille, ou bouton suppr)

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#161]

**Comment by elpiolito** [comment]
Deux questions : 
- Est-ce toujours d'actualité ?
- Est-ce bien utile cette fonctionnalité ? Est-ce que vous vous trompez tellement souvent dans vos uploads que ça nécessite d'avoir la fonctionnalité de suppression ? Perso, je suis moyennement chaud parce que ça laisse ouvert la possibilité de supprimer des images d'autres articles ou les images des fiches séries "sans faire exprès".

**Comment by MarieOphelie** [comment]
Oui, c'est toujours d'actualité.
Oui, ça serait utile. Il y a le même problème pour les dossiers, d'ailleurs. Koss a créé un "nouveau dossier" (par erreur je pense) dans le dossier images de la critique 8.06 de GoT. Ce dossier est complètement inutile, et il y avait d'ailleurs mis une image dedans par erreur. J'ai pu déplacer l'image, mais pas supprimer le dossier. Le risque est que Puck y ajoute aussi des images dedans quand elle écrira sa critique.

Après, si c'est possible techniquement, on peut peut-être restreindre l'autorisation de supprimer des images/dossiers aux admins, si on a peur que certains rédacteurs fassent des fausses manip. Vous en pensez quoi ?

**Comment by GalaxSerieAll** [comment]
+1 avec ML. On fera attention. Et tant qu'il y a un message de confirmation nécessitant bien un deuxième clic ça devrait aller. :)

**Comment by elpiolito** [comment]
Ok, je note.

**Comment by elpiolito** [comment]
La suppression par corbeille ne fonctionne pas, faut que je regarde en détail.
La suppression définitive fonctionne. Elle fonctionne comme sous windows : shift + suppr sur le fichier concerné.

**Comment by youkoulayley** [comment]
C'est corrigé

**Comment by MarieOphelie** [comment]
Merci Elpio du 20 juin qui n'a jamais été remercié mais qui nous avait fourni une solution intermédiaire utile. :)
Et merci Youk d'il y a 4 jours pour la correction définitive !
