### ISSUE TITLE
Alerte bug site : Colonne articles similaires + masquer les articles non-publiés, épisode 2 !! !(cf description)

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#163]
J'ai encore une fois pu avoir accès à ma news jamais publiée sur The Handmaid's Tale saison 2, cette fois-ci avec la colonne "article similaire" en visionnant un article.
Cette colonne est d'ailleurs assez buggée : les titres se superposent aux images, rien n'est aligné.

(désolé cette issue est un peu une double-issue)

**Comment by elpiolito** [comment]
Idem sur la colonne "Derniers articles de la série". Je pense qu'il manque le filtre sur les requêtes
