### ISSUE TITLE
Bug site admin : impossible entrer mots dans la barre de recherche séries depuis un iPad (cf JphMaxx article v2)

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#165]

**Comment by elpiolito** [comment]
Idem sur mon Moto X Style, sous firefox. Je pense à un soucis avec la zone de saisie de la recherche

**Comment by elpiolito** [comment]
Comportement idem chez Galax et Marie Louise sur leurs mobiles
