### ISSUE TITLE
Bug site majeur : disparition totale d'une fiche épisode de Black Mirror S3 E4 (San Junipero)

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#166]
Résoudre le problème dévoilera peut-être d'autres épisodes disparus ?

**Comment by GalaxSerieAll** [comment]
https://serieall.fr/saison/sherlock/4

Cas non isolé : disparition épisode 1 de Sherlock saison 4 !

Point commun avec black mirror :ces deux saisons avaient des épisodes spéciaux, autrefois comptabilisés en épisode 0.

**Comment by youkoulayley** [comment]
Les deux sont résolus
