### ISSUE TITLE
Bug site : planning non mis à jour

### ISSUE THREAD

**Issue by elpiolito** [serieall/serieall#167]
A priori, la mise à jour du planning ne fonctionne pas des masses...

**Comment by youkoulayley** [comment]
A quel niveau, tu as un exemple de ce qui ne va pas ?

**Comment by elpiolito** [comment]
Tout le planning en fait. Là, les quelques séries affichées, c'est moi qui ait forcé la mise à jour de certaines séries pour tester. 
Si tu compares : https://www.spin-off.fr/calendrier_des_series.html

Nous, par exemple, sur le 20/02, on a modern family, chicago pd et chicago fire. On devrait avoir, en plus, chicago med, schooled ou single parents (liste non exhaustive). 
Modern Family et les chicago ne sont là que parce que j'ai appuyé sur le bouton "forcer la mise à jour" depuis tvdb sur les 3 fiches séries, sinon elles étaient vides.

Normalement, à part le samedi ou en période de noel/été, on doit avoir au moins 5 séries par jour minimum par case. Je pense que ça a du planter autour du 10 février parce que c'est à partir de là qu'on a plus grand chose dans les cases (tu peux comparer : le jeudi, on est à plus de 15 séries jusqu'au 7/02 et après, il n'y en a plus que 2-3 séries pour ce jour)

**Comment by youkoulayley** [comment]
Alors si je prends single parents par exemple, l'épisode était marqué pour le 20 mars :p 
Schooled n'était pas à jour non plus.

En fait je pense surtout que c'est du au fait qu'on a beaucoup de séries qui étaient renseignées manuellement avant, ou que le système de mise à jour des séries fonctionne en même temps que les mises à jour de TVDB. Faudrait que je lance une maj sur toutes les séries du site, mais j'ai peur que ça fasse du dégat sur les anciennes. Je vais essayer de faire ça petit à petit.

**Comment by elpiolito** [comment]
Ouep, ça ne me surprend pas qu'il y ait de la cafouille vu comment c'était géré ^^
Fais au mieux, de toute façon, personne n'a l'air de s'en être rendu compte à part moi !

**Comment by MarieOphelie** [comment]
Mdr coucou ! Moi aussi je m'en suis rendue compte. :) (et je n'ai rien dit car ça ne m'impacte pas directement, vu que je suis une grosse feignasse qui ne note pas les séries qu'elle regarde)
Cela dit je suis d'accord avec Elpio : fais au mieux, Youk <3

**Comment by elpiolito** [comment]
Mauvaise commande sur le Cron ou Cron mal configué. Remplacé par la commande queue:work -once, à voir ce qu'il se passe.

**Comment by elpiolito** [comment]
Pas un problème de mauvaise commande dans le cron. Peut-être un problème de date de départ pour la mise à jour.

**Comment by elpiolito** [comment]
A priori ok
