### ISSUE TITLE
Accès aux pages paramètres/notifications et planning d'un utilisateur

### ISSUE THREAD

**Issue by elpiolito** [serieall/serieall#170]
Lorsque l'on accède à sa page profil, en tant que nouveau membre, les pages planning, notifications et paramètre sont inaccessibles, on reste sur la page sur laquelle on était.
L'accès direct en remplaçant l'url ne fonctionne pas et redirige vers une page captcha.
Ajouter une série en cours dans la liste des "je regarde" ne change rien.

**Comment by youkoulayley** [comment]
J'ai pas le soucis de mon côté, tu as créé l'utilisateur dans l'admin ou via l'inscription ?

**Comment by youkoulayley** [comment]
Ok, j'ai testé avec ce user, effectivement y'avait un soucis, je l'ai fixé
