### ISSUE TITLE
Bug majeur site version mobile : la barre de recherche séries ne fonctionne pas du tout !

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#173]
Elle apparaît mais ne réagit pas quand on clique dessus.
Testé sur mon portable (Huawei avec Chrome).

**Comment by MarieOphelie** [comment]
Tiens en effet, c'est revenu. Alors que ça avait été réglé je crois, en tout cas j'avais fait des tests il y a quelques jours (semaines ?) et la barre de recherche fonctionnait

**Comment by elpiolito** [comment]
Duplication avec : https://github.com/serieall/serieall/issues/165
Je clos
