### ISSUE TITLE
Admin : mettre texte des articles en alignement justifié par défaut (si possible)

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#174]

**Comment by elpiolito** [comment]
Par défaut, tous les articles publiés sur le site sont justifiés donc **ne surtout rien faire** sur l'interface de saisie depuis l'admin pour essayer de mettre en justifié : ça va juste mettre la grouille plus tard si on fait des changements.
Je regarde pour que ce soit aussi justifié sur l'interface d'admin

**Comment by MarieOphelie** [comment]
Ah ben c'est trop tard, lors de me relectures des premiers articles j'ai "forcé" la justification (je ne savais pas que le site le faisait par défaut :/)

**Comment by elpiolito** [comment]
Oui, j'ai vu. Tant pis, pour les prochaines fois, tu sauras : seule la vérification de la mise en forme via le site fait foi, les éditeurs de texte c'est la merde pour ça, il y a jamais rien de conforme. Pour ça qu'il faut pas vous laisser trop de bouton aussi :)

En touts cas, je ne trouve pas l'option pour mettre l'éditeur admin en justifié par défaut, c'est con.

**Comment by MarieOphelie** [comment]
_"Pour ça qu'il faut pas vous laisser trop de bouton aussi :)"_
Sur la V1, on avait aussi ces boutons, et ils étaient... utiles. Car les news, par défaut non justifiées dans l'admin, s'affichaient non justifiées aussi sur le site. :)

Je préviens Galax, car sur sa dernière news il a automatiquement mis en justifié vu qu'il avait connaissance du problème

**Comment by youkoulayley** [comment]
Il y a toujours quelques chose à faire là dessus du cuop ?

**Comment by MarieOphelie** [comment]
Écoute non ça ira, dans la mesure où même si ce n'est pas justifié dans l'admin, ça s'y met automatiquement sur le site. Maintenant je fais la chasse aux personnes qui forcent la justification dans l'admin. :p
