### ISSUE TITLE
Enhancement site : pop-up fenêtre rédaction (ou modification) d'un avis - plusieurs changements, cf description

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#176]
- Ajouter une croix en haut à droite afin d'offrir une possibilité claire aux utilisateurs de quitter la page (au lieu de "cliquer ailleurs")
- Créer 3 "choix"/"cases à cocher"  pour la liste avis "favorable/neutre/défavorable" au lieu du menu déroulant actuel (permet d'économiser un clic)
- Mettre un avis favorable par défaut.

**Comment by youkoulayley** [comment]
![image](https://user-images.githubusercontent.com/2247492/66203179-f96b5a80-e6a7-11e9-9ed2-d9a702438abb.png)
Ceci vous convient-il ?
