### ISSUE TITLE
Admin : suite de la conversation lors d'une prise de contact via le formulaire à basculer sur l'adresse du site (serieall.fr@gmail.com) au lieu de l'adresse de l'association

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#178]
![image](https://user-images.githubusercontent.com/19188496/54257344-51514100-455f-11e9-9eff-25179d16c043.png)

**Comment by elpiolito** [comment]
Juste pour préciser : le mail est envoyé aussi avec l'adresse de l'association ou c'est juste une erreur de libellé ?

**Comment by MarieOphelie** [comment]
Je ne sais pas du tout. Il faudrait faire un test pour voir

**Comment by MarieOphelie** [comment]
Ok, test fait, c'est l'adresse "journeytotheit@gmail.com" qui répond : 
![image](https://user-images.githubusercontent.com/19188496/54271203-5cb56400-4581-11e9-8d75-4f4447975b28.png)

J'ai répondu à ce mail, et rien n'a été reçu sur l'adresse de l'asso (ni sur l'adresse du site).

**Comment by elpiolito** [comment]
Ok, il y a du nettoyage à faire alors, l'adresse est le compte de test de Youk.

**Comment by elpiolito** [comment]
Bacsule sur le compte serieall.fr effectuée.
Reste à nettoyer l'ancienne adresse du site et le message.

**Comment by MarieOphelie** [comment]
D'ac' c'est déjà bien, merci chouchou !
