### ISSUE TITLE
Données non migrées

### ISSUE THREAD

**Issue by elpiolito** [serieall/serieall#179]
Il manque différentes données qui n'ont pas été migrées de l'ancien serveur :

- Podcasts
- Images des séries (elles sont utilisés dans les articles, notamment le VrickAVrack)

**Comment by elpiolito** [comment]
En attente de Youkoulayley

**Comment by youkoulayley** [comment]
Ah fuck, je vais m'en occuper aussi !

**Comment by youkoulayley** [comment]
https://serieall.fr/podcasts/Bilan%20-%20Westworld%20S2.mp3
Quel bonheur d'entendre la voix de ce cher Koss.

J'ai normalement tout recopié. Si vous voyez toujours des manquants, dites moi :p
