### ISSUE TITLE
Avis : peut-on supprimer le nombre de caractères minimum lorsqu'on répond à un avis ?

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#185]
![LimitesCaracteres](https://user-images.githubusercontent.com/19188496/55979091-aa60e180-5c91-11e9-99aa-849444ee3afc.jpg)

(c'est pas mon screenshot) (mes noms de conv messenger sont beaucoup plus badass que ça)

**Comment by GalaxSerieAll** [comment]
(c'est une référence au Doctor Who nul de Chibnall dans la saison 11)
(il a fait un épisode où des Daleks sont détruits par l'amour et un micro-onde....)
(tu as lu ça et as acquis du savoir sur DW, derien)

**Comment by MarieOphelie** [comment]
J'ai lu "référence au Doctor Who **nu** de Chibnall". J'étais presque prête à regarder la saison 11...

(Des Daleks détruits par l'amour et UN MICRO-ONDES mais bordel. Bordel.)

**Comment by elpiolito** [comment]
Possible.

**Comment by elpiolito** [comment]
Réduit à 3, pour éviter le spam.
