### ISSUE TITLE
Articles - afficher uniquement la date d'écriture (ou de première publication ?), pas la date de la dernière mise à jour

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#187]
Exemple :

L'article easter-eggs de Koss a été écrit et publié en 2015 :

![image](https://user-images.githubusercontent.com/19188496/56466877-e6294300-6417-11e9-8512-5aa29cbc19ba.png)

Je viens de le mettre à jour, et du coup la date qui s'affiche maintenant sur l'article est fausse (c'est celle d'aujourd'hui) :

![image](https://user-images.githubusercontent.com/19188496/56466885-0f49d380-6418-11e9-86a5-4cb57ba1d152.png)

**Comment by elpiolito** [comment]
Par contre, on garde l'ordre de l'affichage des articles selon la date de dernière modification ?

**Comment by elpiolito** [comment]
Note : la date d'écriture est la date de création dans la base. C'est à dire, genre pour les VaV, si l'article est initié le 10/04 mais publié que le 25/04, la date d'écriture c'est le 10/04. Ok avec ça ?

**Comment by MarieOphelie** [comment]
_> Par contre, on garde l'ordre de l'affichage des articles selon la date de dernière modification ?_

Non, si on pouvait aussi éviter ça, ça serait génial. :) Histoire que les vieux articles ne se retrouvent pas en home alors qu'on voulait juste corriger une coquille, par exemple.


_> Note : la date d'écriture est la date de création dans la base. C'est à dire, genre pour les VaV, si l'article est initié le 10/04 mais publié que le 25/04, la date d'écriture c'est le 10/04. Ok avec ça ?_

Dans l'idéal de l'idéal d'un site parfait et merveilleux, je pense qu'il serait plus pertinent d'avoir :
- côté admin : date d'écriture de l'article (comme actuellement), date de modification (qu'il faudrait rajouter) et date de première publication ;
- côté visiteur : uniquement la date de première publication.
Mais ça c'est vraiment dans un monde parfait. Si ce n'est techniquement pas possible : garder dans la partie visiteur uniquement la date de création dans la base, tant pis s'il y a parfois quelques jours de décalage.

**Comment by elpiolito** [comment]
C'est possible je pense mais ça demande du boulot la date de publication : les deux autres sont automatiquement gérées en fait par le framework, la date de publication non donc tout est à gérer manuellement.
Un jour peut-être.

**Comment by MarieOphelie** [comment]
D'ac, pas de souci. Du coup en attendant, est-ce qu'on peut rebasculer quand même sur la solution "facile", à savoir que la date de publication affichée soit celle de création dans la base ?

**Comment by elpiolito** [comment]
@youkoulayley avait fait le gros du travail sur la date de publication, il fallait juste rajouter un test pour ne pas remettre la date de publication à jour quand c'était déjà publié :)
Donc, les articles sont triés par date de publication sur la home, la date de publication est affichée sur l'article et ce n'est pas remis à jour à chaque modif après. Donc tu peux corriger des coquilles sur d'anciens articles, ils ne remonteront plus, normalement.

**Comment by MarieOphelie** [comment]
Génial, merci beaucoup ! Vous gérez <3
