### ISSUE TITLE
Admin - module de rédaction : ajouter bouton HTML pour qu'on puisse voir le code de l'article + bouton espace insécable (si possible)

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#188]

**Comment by MarieOphelie** [comment]
HTML : certains rédacteurs se merdent un peu au moment du copier-coller je pense, et il y a parfois des trucs chelous dans leurs articles. Sur l'ancienne admin, je jetais trèèèès souvent un œil au html pour supprimer des trucs en trop qui faisaient cafouiller la présentation. Là, je me galère à trouver d'où vient le problème, parfois je suis obligée de supprimer tout le paragraphe et de le recopier, bref : je perds du temps. :)

Espace insécable : ai-je besoin de préciser la finalité ? Certaines ponctuations se retrouvent parfois à la ligne parce que l'espace qui se trouve avant n'est pas insécable. Dans l'ancienne admin, il était dispo dans le bouton "Insérer un caractère spécial", là il n'existe plus. Et encore mieux : à mon boulot, j'ai un bouton EXPRÈS pour ça, qui m'évite d'avoir à ouvrir les caractères spéciaux :

![image](https://user-images.githubusercontent.com/19188496/56734795-1fd5b300-6764-11e9-8ce0-45b359094838.png)

Mais disons que s'il est accessible dans les caractères spéciaux, ça sera déjà top. :)

**Comment by elpiolito** [comment]
Solution : suppression de toute la mise en forme, uniquement titre, liste et gras. Problème solved 🤣 
Et alignement à droite parce que le justifié c'est le mal. Problème d'espace insécable solved too

Je jetterais un oeil un jour.

**Comment by MarieOphelie** [comment]
Ok, donc ça veut dire qu'on ne peut plus rien mettre en italique ? Ni de texte en exposant ? Ni centrer les images et leurs légendes ? Ni mettre du texte en couleur (Nick met les noms des rédacteurs en couleur dans le VaV) ?
Dis, chouchou... tu veux ma mort ??
(Et les liens hypertextes ? Tu considères que c'est de la mise en forme ou pas ?)

Pour l'alignement à droite, ça apparaîtra aussi aligné à droite sur le site ? (L'option justifié on n'y touche plus depuis que tu nous as dit que par défaut, le texte apparaissait en justifié sur le site ; donc dans l'admin il est bien aligné à gauche.)

**Comment by elpiolito** [comment]
Ha ha, calm down.
L'idéal, c'est moins vous en faites, mieux c'est. Parce que dès que vous vous essayez à la mise en forme, c'est moche, ça ressemble à rien, c'est péter de partout un coup sur deux. Donc franchement, je ne serais d'avis que de vous laisser le minimum syndical parce que côté dev, c'est ingérable (t'as qu'à reprendre des vieux articles). 
Donc le minimum, c'est le HTML pur, point, et le reste c'est gérer par le site. Tous les articles ont la même tête, plus besoin de se poser de question sur les mises en forme, etc. Gain de temps pour tous.

maintenant, comme je sais que dès qu'on dit qu'on va supprimer un truc, il y a des levées de bouclier, ça reste comme ça. mais franchement, vous n'avez vraiment pas besoin de mise en forme, juste le fond.

**Comment by MarieOphelie** [comment]
> _maintenant, comme je sais que dès qu'on dit qu'on va supprimer un truc, il y a des levées de bouclier, ça reste comme ça. mais franchement, vous n'avez vraiment pas besoin de mise en forme, juste le fond._

Ben si tu arrives à nous mettre en place une trame où toute la mise en forme est faite automatiquement sans qu'on n'ait plus rien besoin de faire... il n'y aura sans doute pas de lever de boucliers, au contraire. :p
Par contre, si "ça reste comme ça" et que la mise en forme se fait encore à la main quelques temps : pourrais-je stp avoir accès au code html des articles + avoir un bouton espace insécable en attendant ? :)

**Comment by elpiolito** [comment]
Oui, un jour, c'est loin d'être une priorité :-)

**Comment by MarieOphelie** [comment]
Bon, alors.
C'est peut-être loin d'être une priorité pour toi, hein. Ce que je comprends. Mais là, franchement Elpio, le code HTML des articles serait **plus que bienvenu**.

Je viens de me taper la relecture de deux critiques du même épisode de GoT (double-critique qui n'était absolument pas prévue et qui tombe extrêmement mal au vu de mon planning perso plutôt surchargé). Ces deux critiques comportaient exactement le même coin du fan. Une fois ce coin du fan corrigé dans le premier article, j'ai fait un copier-coller pour ne pas avoir à me taper une deuxième correction dans le deuxième article.
Sauf que, haha tu vas rigoler (moi je rigole pas trop, tu peux le constater), la mise en page se barre lors d'un copier-coller du texte "simple".
Si j'avais pu copier-coller le code html, je n'aurais pas eu besoin de me retaper la mise en page sur le deuxième article. J'aurais donc perdu beaucoup moins de temps.

Quand Youk nous a montré ce nouveau module sur l'ancien forum lors de la mise en place de la V2, on avait pu faire le choix des boutons à garder/à supprimer. Je reste persuadée que JAMAIS je n'aurais demandé la suppression du html. Et quand bien même ça aurait été le cas, l'accès aux différents boutons ne semblait pas prendre énormément de temps à modifier.

Donc, je réitère une dernière fois : peux-tu, s'il te plaît, remettre le bouton HTML dans le module de rédaction ?

(Parce que là, ça me fait un peu mal qu'on puisse considérer que mon temps personnel n'est pas une priorité et n'est juste qu'un simple "bug cosmétique", tu vois.)

:-)

**Comment by elpiolito** [comment]
J'ai bien pris note mais il y a eu des choses plus pressées a régler avant (les soucis de lenteur notamment qui empêchaient l'accès au site) et là, perso, je n'ai plus le temps de m'en occuper avant au moins la fin du mois au mieux. Désolé

**Comment by elpiolito** [comment]
Ok pour le bouton source.

Par contre, je ne comprends pas tes problèmes de mise en page : quand je copie colle le texte mis en forme d'un article à l'autre, j'ai pas de perte de la mise en forme. Cela copie-colle même les images : tu pourras me dire ce que tu t'y es pris pour que ça merdouille ?

Pour l'espace insécable, je ne le trouve pas, ça sera corrigé plus tard.

Autre question, tant qu'on est sur les boutons : il y a un corrcteur orthographique qui peut etre activé. Cela envoie le texte sur un service externe SpellChecker.net pour faire l'analyse. Dois-je activer ou pas ?
L'avantage, c'est que ça soulignera rouge les fautes d'orthographe et les fautes de frappe : ça simplifiera le boulot du relecteur. L'inconvénient, c'est que le texte est envoyé à un service externe (et il y a une pub affichée à côté du correctif quand tu fais un clic droit) mais est-ce un soucis, sachant que l'on publiera l'article ?

**Comment by MarieOphelie** [comment]
_> Ok pour le bouton source._
Raaah MERCI Elpio, merci. <3 Merci beaucoup. <3 <3

> _Par contre, je ne comprends pas tes problèmes de mise en page : quand je copie colle le texte mis en forme d'un article à l'autre, j'ai pas de perte de la mise en forme. Cela copie-colle même les images : tu pourras me dire ce que tu t'y es pris pour que ça merdouille ?_
Alors, de mémoire (de l'eau a passé sous les ponts depuis) : les images se collaient bien, oui effectivement, mais ne restaient pas centrées. Il y avait un souci également avec les paragraphes que j'avais mis en "retrait" (le coin du fan est composé de puces. quand on fait un retour à la ligne mais qui concerne toujours le même point, je supprime la nouvelle puce créée mais ajoute un retrait pour que le texte soit bien aligné sur le paragraphe du dessus (pas sûre que mon explication soit claire)). Le texte qui avait été centré se retrouvait aligné à gauche aussi, je crois. Et - mais là je ne suis plus sûre sûre donc je dis peut-être une bêtise - il me semble que les citations n'étaient pas gardées en mode citation.

**Comment by MarieOphelie** [comment]
> _Autre question, tant qu'on est sur les boutons : il y a un corrcteur orthographique qui peut etre activé. Cela envoie le texte sur un service externe SpellChecker.net pour faire l'analyse. Dois-je activer ou pas ?
L'avantage, c'est que ça soulignera rouge les fautes d'orthographe et les fautes de frappe : ça simplifiera le boulot du relecteur. L'inconvénient, c'est que le texte est envoyé à un service externe (et il y a une pub affichée à côté du correctif quand tu fais un clic droit) mais est-ce un soucis, sachant que l'on publiera l'article ?_

Mmmmh pourquoi pas, oui. S'il y a juste une pub au moment du clic droit et pas partout dans l'article pendant que tu relis, oui ça pourrait être utile en effet. :)
Et le texte envoyé au service externe, je suis d'accord avec toi : de toute manière nos articles sont publics, donc bon, on n'a rien de confidentiel.
Merci !

**Comment by elpiolito** [comment]
Pas de bouton pour espace insécable.
Le seul truc que j'ai trouvé, c'est un plugin qui te rajoute un espace insécable en faisant un CTRL + Espace
Pas mieux pour le moment.
