### ISSUE TITLE
Wiki - impossible d'accéder au wiki, il propose un fichier "téléchargement" à enregistrer quand on clique dessus

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#189]
![image](https://user-images.githubusercontent.com/19188496/56862194-89460380-69a8-11e9-807d-1737fdffa3cf.png)

![image](https://user-images.githubusercontent.com/19188496/56862208-af6ba380-69a8-11e9-923d-88b13a04cb65.png)

**Comment by elpiolito** [comment]
Voir avec Youkoulayley

**Comment by youkoulayley** [comment]
Damn, je m'en occupe, j'en profiterai pour le migrer aussi sur une adresse serieall.fr :smile:

**Comment by MarieOphelie** [comment]
Super, merci Youk !

**Comment by youkoulayley** [comment]
Wiki is back on wiki.serieall.fr.

**Comment by MarieOphelie** [comment]
Mmmmh non, ça ne fonctionne toujours pas. :(

![image](https://user-images.githubusercontent.com/19188496/58955168-7559a280-879b-11e9-8914-c37c655c05bc.png)

**Comment by youkoulayley** [comment]
Et maintenant ?

**Comment by MarieOphelie** [comment]
Ouiiiiiiiiiiiii ! \o/
