### ISSUE TITLE
Enhancement site - indiquer nouveaux articles dans le fil d'actu avec un logo attractif (couleur chaude rouge/jaune pour trancher avec le reste par exemple) et le laisser en première position pendant quelques temps ? (si possible)

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#194]

**Comment by elpiolito** [comment]
Ok pour ajout dans le fil d'actu.
Par contre, quelle finalité pour l'avoir de toujours visible en haut ?

**Comment by GalaxSerieAll** [comment]
Je n'ai pas bien compris ta question :/ 
Je trouve que les nouveaux articles, surtout sur mobile, passent inaperçus. Idéalement une case avec un "nouvel article" s'insère au-dessus des notes/avis/réponses, et tout nouvel article écrase l'ancien et le remplace. Si aucun nouvel article au bout de 7 jours (par ex), alors on supprime le bloc (vu qu'il ne sera plus nouveau, le dernier article paru) et ça redevient comme maintenant, jusqu'au prochain
(si pas possible de mettre une variable temps, tant pis tant pis)

**Comment by elpiolito** [comment]
En gros, tu veux que la zone article soit avant le fil d'actu parce que tu n'arrives pas à distinguer les nouvelles critiques Game of Thrones quand tu es sur ton téléphone ? Tu veux dupliquer les zones articles, c'est ça ? Et juste une notif dans le fil d'actu du genre "Galax a écrit un nouvel article sur Game of Thrones", c'est pas suffisant ?

Je comprends pourquoi tu veux le faire, maintenant je n'en suis pas super fan : ça fait des doublons partout et ça devient donc illisible pour le visiteur qui ne sait pas trop où regarder. Et en rajoutant une zone, tu vas me dire ensuite que les dernières notes/avis ne sont pas visibles :p
(Petite précision en passant : tout ce qui est visible sur mobile, c'est visible sur desktop. Donc une zone supplémentaire sera visible sur les deux...)

Après, la question c'est toujours la même depuis des années (j'ai surement eu ce débat avec tous les membres du site je pense) : doit-on prioriser les articles ou la communauté ?

**Comment by MarieOphelie** [comment]
> _Après, la question c'est toujours la même depuis des années (j'ai surement eu ce débat avec tous les membres du site je pense) : doit-on prioriser les articles ou la communauté ?_

Normalement, ce débat était clos (sur l'ancien forum, impossible de retrouver l'échange) : la priorité est à donner à la communauté, car c'est elle la plus "active". En dehors des périodes GoT / BCS / Westworld, c'est surtout les notes et avis des membres qui font vivre le site, pas les articles malheureusement.

> _Et juste une notif dans le fil d'actu du genre "Galax a écrit un nouvel article sur Game of Thrones", c'est pas suffisant ?_

Cette idée de notif dans le fil d'actu est plutôt bonne en compromis je trouve, non ? :)

**Comment by elpiolito** [comment]
Pour moi, la notif serait suffisante mais j'attends confirmation :)
Du coup, on pourrait imaginer ajouter un filtre dans le fil du genre "articles" qui listeraient les notifs du genre "galax a écrit un nouvel article" et les "jean louis a déposé un commentaire sur la critique de XXX, histoire de séparer les deux.

**Comment by MarieOphelie** [comment]
Oui, je trouve que c'est vraiment une bonne idée !

**Comment by GalaxSerieAll** [comment]
Une notif ça serait cool et idéal oui ! C'est une bonne solution :)
Avec un bon code visuel en revanche : actuellement le code couleur vert/gris/rouge + le symbole du smiley sert bien à distinguer quand quelqu'un dépose un avis d'une autre "note sans avis", pour les articles ça serait bien un truc jaune/orange par exemple, du genre : 
"Galax a écrit un [logo] **nouvel article** "Critique GOT"".

Et en effet ajouter un troisième critère de "tri" du fil d'actu serait bien. Dans le V1 yavait note, avis et commentaires je crois, non ? Là on a juste note et avis.

**Comment by youkoulayley** [comment]
les articles apparaissent maintenant dans le fil d'actu : 
Exemple avec un article écrit par plusieurs personnes et un article écrit par une seule personne:
![image](https://user-images.githubusercontent.com/2247492/72159999-dc88a680-33bd-11ea-93d7-134899a09adc.png)
