### ISSUE TITLE
Bug cosmétique site : pour tous les "anciens" avis qui étaient sous spoilers, une parenthèse fermante ouvre chaque avis, suivie par le spoiler. cf commentaire

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#207]
Exemple : https://serieall.fr/episode/docteur-who-2005/s8e4?page=1

Si pas possible de la supprimer sans risquer de supprimer tous les avis ou autre bug chelou, possible de la remplacer par quelque chose comme "Spoiler" ou même : "(Spoilers)" pour réutiliser cette parenthèse à bon escient. ?

**Comment by elpiolito** [comment]
C'est une faute de frappe qui a du rester traîner quelque part. Je corrigerai
