### ISSUE TITLE
Bug / Question : la MAJ des séries depuis TVDB fonctionne-t-elle ? J'ai forcé la maj de certaines séries (Timeless, American Crime Story) pour que les fiches épisodes soient mises à jour (résumé, scénariste etc.) et ça a tout de suite marché : preuve que ce n'était pas fait automatiquement avant ?

### ISSUE THREAD

**Issue by GalaxSerieAll** [serieall/serieall#208]

**Comment by elpiolito** [comment]
Tu sais que tu peux détailler ta question en description plutôt que de tout coller dans le titre ? On dirait un vieux qui sait pas écrire des mails :p 

Plus sérieusement, à priori, elle fonctionne puisque le planning est toujours rempli et à jour : si ça déconnait, le planning serait dans les choux.
Maintenant, la mise à jour n'est que la mise à jour du delta entre deux mises à jour, pas une mise à jour complète. 
Par exemple, si entre aujourd'hui et demain, il n'y a que Doctor Who qui est mis à jour sur TVDB, il n'y aura que Doctor Who de mis à jour sur le site et uniquement les épisodes qui ont été mis à jour sur TVDB, pas les autres. Sinon, si on devait faire la mise à jour complète de la base, ça prendrait des heures pour rien vue qu'entre aujourd’hui et demain, on sait qu'il n'y aura que des modifs à faire sur doctor who.
Maintenant, cette méthode suppose que le site soit à jour, ce qui n'est pas le cas. 
Les séries passées et qui n'ont pas été mises à jour depuis longtemps sur TVDB ne sont pas mises à jour chez nous puisqu'on n'a pas été notifié de modifications. C'est surement le cas pour Timeless ou ACS qui n'ont pas du subir de modification depuis quelques mois. PAs de modif, pas de notif. PAs de notif, pas de mise à jour.

Il faut dans l'idéal qu'on lance une grosse synchro complète de la base de données pour remettre tout à jour mais pour le moment, comme c'est un poil risqué (on risque de péter toute la base quand même), faut que je la teste plusieurs fois pour être sûr avant de le faire en vrai. PArce qu'il y aura forcément des soucis de doublons (comme c'est déjà le cas sur certaines séries) mais ça ne va pas être les seuls.

Bref, si tu vois une série pas à jour, si ça date de l'an dernier les derniers épisodes et qu'il n'y a pas de nouveaux prévus dans les 3 jours, c'est surement normal que ce soit déphasé et tu peux la resynchro à la main.

Je clôture.
