### ISSUE TITLE
Optimiser les temps de chargement

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#212]
Je cite Elpio :
> Je serais d'avis aussi de faire un peu d'optim sur les temps de chargement parce que là, c'est longuet quand même. J'ai mis en cache quelques trucs mais je pense qu'il serait bien de faire une passe d'optimisation sur les images notamment, histoire de réduire le poids des pages et tout charger plus vite, ou faire du lazy loading.

**Comment by youkoulayley** [comment]
Le poids des images a été grandement réduit, je ferme cette issue, y'a encore plein d'otpims à faire mais je vais créer ce qu'il faut au moment ou je pourrai les traiter :)
