### ISSUE TITLE
Plantage suite à accès aux pages de Mr Robot et Love Death and Robots

### ISSUE THREAD

**Issue by elpiolito** [serieall/serieall#218]
L'accès à ces pages semble faire planter le site pendant plusieurs minutes (page blanche et rien au rechargement).
Comportement à priori aléatoire et non reproductible aisément (cause non identifiée pour le moment) mais identifié par plusieurs membres. 

Piste possible : les noms des épisodes comportent des caractères spéciaux, peut-être un soucis d'encodage ou de mauvais échappement dans certains cas.

Checker les logs : s'il y a plantage du site, ça doit se voir :)

**Comment by youkoulayley** [comment]
La configuration du fail2ban bloquait les erreurs sur les urls qui contenaient "(b|B)ot", j'ai modifié la regex et ça devrait être mieux.

**Comment by elpiolito** [comment]
Ah merde, c'est moi qui avait mis ça en place à l'arrache quand le serveur ramait sous les coups des bots de referencement. 
my bad :p
