### ISSUE TITLE
Admin - Ajouter le champ TVDBID dans la page d'édition des séries

### ISSUE THREAD

**Issue by elpiolito** [serieall/serieall#220]
Ajouter le champ TVDBId dans les pages d'admins de modification des séries pour pouvoir corriger les erreurs de saisie sans devoir systématiquement passer par la base de données.
Ne l'ajouter que pour les profils admin pour éviter les erreurs de la part des membres "qui ne savent pas trop"

**Comment by youkoulayley** [comment]
Done
