### ISSUE TITLE
Accès http mal configuré

### ISSUE THREAD

**Issue by elpiolito** [serieall/serieall#244]
Quand on essaye d'accéder à serieall par accès http, il propose de télécharger un fichier plutôt que de rediriger vers https.

Pour test : prendre un navigateur en navigation privée, taper serieall.fr : téléchargement de fichier.
/!\ si ça redirige bien vers https, c'est que le navigateur y a déjà accéder. Essayer avec un navigateur sans l'adresse serieall dans son cache :)

**Comment by youkoulayley** [comment]
Corrigé, y'avait un "listen 80 http2;" qui trainait, forcément ça marche pas trop :p
