### ISSUE TITLE
Admin - Impossible de supprimer le compte d'un membre

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#247]
Le membre Mmattia a demandé à ce que son compte soit supprimé ; je tombe sur une page error 404 lorsque j'essaye de le faire (alors que jusqu'à présent ça avait toujours fonctionné)

**Comment by youkoulayley** [comment]
Alors je sais pas pourquoi, il arrivait pas à supprimer une de ses notes.
C'est corrigé et j'ai supprimé le compte

**Comment by MarieOphelie** [comment]
Merciiii beaucoup ! <3
