### ISSUE TITLE
Responsive - fiches épisodes

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#71]
Il y a une ligne qui traverse le bouton "Lire l'avis complet"

![1542789585-screenshot-2018-11-21-07-28-29](https://user-images.githubusercontent.com/19188496/48884515-1ba81100-ee25-11e8-8979-83fb7aed2a48.png)

**Comment by youkoulayley** [comment]
Même après MAJ de semantic ui (système de design), je n'arrive pas à virer cette ligne déguelasse.
Du coup pour le moment je vais laisser comme ça, j'arrive pas à trouver ou l'enlever :'(
