### ISSUE TITLE
Responsive - 2 problèmes sur filtres de la page "Liste des séries"

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#79]
1. Les filtres par chaîne, nationalité et genre ouvrent le clavier au moment du choix, mais ne le font pas disparaître une fois la recherche effectuée (ce qui donne l'impression que la recherche n'est pas faite) :

![screenshot_2018-11-25-09-02-22](https://user-images.githubusercontent.com/19188496/48981672-f80cf100-f0d8-11e8-82a1-6c4f15d05066.png)

![screenshot_2018-11-25-09-04-28](https://user-images.githubusercontent.com/19188496/48981673-f8a58780-f0d8-11e8-9c90-d7b0d6e8ddd7.png)

![screenshot_2018-11-25-09-05-15](https://user-images.githubusercontent.com/19188496/48981674-f8a58780-f0d8-11e8-9298-b90bc07edfbf.png)

2. La croix de fermeture du filtre "Trier" ne fonctionne pas ; quand on clique dessus rien ne se passe :

![screenshot_2018-11-25-09-06-33](https://user-images.githubusercontent.com/19188496/48981688-2a1e5300-f0d9-11e8-8416-120270429ecb.png)

**Comment by youkoulayley** [comment]
Pas sur que je puisses faire quelque chose là dessus, ou alors il faudrait que je vire la partie recherche et ne laisser que la liste déroulante, mais je pense que ce serait chiant à utiliser, tu en penses quoi ML ?

**Comment by MarieOphelie** [comment]
Arf non en effet, une liste déroulante risquerait sans doute d'être pénible. Tant pis, si tu ne peux rien modifier, autant laisser comme ça dans la mesure où ça ne bloque pas les recherches. :) Merci d'avoir regardé !

**Comment by elpiolito** [comment]
Mettre un bouton recherche et ne lancer le filtre qu'à l'appui ?
