### ISSUE TITLE
Responsive - "Séries abandonnées" sur profil perso

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#82]
Les vignettes des séries abandonnées sont toutes petites comparées aux images des autres types de séries (en cours, en pause, etc.) qui sont plus en mode "couverture" :

![screenshot_2018-11-25-09-19-25](https://user-images.githubusercontent.com/19188496/48981867-21c71780-f0db-11e8-9aa8-05918cd5d44f.png)

**Comment by youkoulayley** [comment]
Corrigé avec le format bannière
