### ISSUE TITLE
Responsive - "Notes" et "Avis" sur profil perso

### ISSUE THREAD

**Issue by MarieOphelie** [serieall/serieall#84]
Dans les parties "Notes" et 'Avis" du profil perso, les colonnes des séries concernées (tout en bas de la page) sont très très fines, ce qui fait que le texte déborde de partout :

![screenshot_2018-11-25-09-24-29](https://user-images.githubusercontent.com/19188496/48981948-027cba00-f0dc-11e8-83c0-e56efc4243f7.png)

![screenshot_2018-11-25-09-24-46](https://user-images.githubusercontent.com/19188496/48981950-027cba00-f0dc-11e8-8323-b9f9742a0ac3.png)

**Comment by MarieOphelie** [comment]
Je vois que le bug est fermé, mais même si le problème côté "Notes" a bien été réglé (merci beaucoup, ça en jette avec la nouvelle mise en page !), j'ai toutefois toujours le problème côté "Avis" : 

![Screenshot_2019-05-25-12-05-28](https://user-images.githubusercontent.com/19188496/58367945-c2a95a80-7ee5-11e9-80b6-e5524948ad04.png)

**Comment by elpiolito** [comment]
Ah merde, j'avais pas vu pour les avis :(
